export default [
  {
    'songId': 1,
    'songImg': 'assets/1.png',
    'songLyrics': [
      'I howl at the moon',
      'It never calls back to me',
      'Just stares and slows',
      'I’d rip it down If I could',
      'Tell me you can hear me',
      'Tell me you’ll be back tomorrow',
      'Don’t let me see a different side of you',
      'Until I say I’m ready',
      'Keep your distance',
      'But don’t go too far',
    ],
    'songTitle': 'Stare And Slow',
  },
  {
    'songId': 2,
    'songImg': 'assets/2.png',
    'songLyrics': [
      'Throw up my arms',
      'Scream for rain',
      'For anything',
      'For a chance to keep the dust at bay',
      'I won’t breathe copper, dirt of centuries',
      'Cough it out before it weighs me down',
      'Carve the past',
      'In trees that drown in the floods',
      'Claw at the banks',
      'Churn the mud and debris',
      'Stand at the edge',
      'Wait to cross',
      'Stare at the edge',
      'At the loss',
    ],
    'songTitle': 'Pneumo',
  },
  {
    'songId': 3,
    'songImg': 'assets/3.png',
    'songLyrics': [
      'Breathe deep and swear to me you won’t disappear too soon',
      'Blow the mist from your lungs',
      'Cough out the fog',
      'You are more than the storm inside your chest',
      'Lay still like the pause between lightning and thunder',
      'Come back to us with a voice you never had',
    ],
    'songTitle': 'For Rain',
  },
  {
    'songId': 4,
    'songImg': 'assets/4.png',
    'songLyrics': [
      'Love and fear are digging roots inside of me',
      'It’s not a home when it’s overgrown',
      'I don’t know what parts are my own',
      'I bloom and grow',
      'All I wanted was to be alone',
      'Now I’m breaking through the floorboards',
      'I scale the walls',
      'All I wanted was to be alone',
      'Shatter the windows and lock the door',
      'I don’t know what parts are my own',
      'It’s not a home when it’s overgrown',
      'All I wanted was to be alone',
      'All I wanted was to be alone',
      'Stay underground',
      'Wait out the cold',
      'I never knew what I’d sown',
      'It’s not a home when it’s overgrown',
    ],
    'songTitle': 'Bloom / Grow',
  },
];
